[package]
name = "data_ingestion_microservice"
version = "0.1.0"
edition = "2021"

[dependencies]
log = "0.4"
pretty_env_logger = "0.4"
redis = "0.29.0"
rumqttc = "0.24.0"
tokio = { version = "1", features = ["full"] }

[[bin]]
name = "asyncpubsub"
path = "src/asyncpubsub.rs"
